/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.jukebot;

import java.io.File;

public class App
{
    public static void main(String[] args)
    {
        File path = new File(args[0]);
        
        Jukebot jukebot = Jukebot.getInstance();

        jukebot.load(path);
        jukebot.play();
        
    }
}
